import Link from "next/link";
const items=[
 {name:"Anderson Glitz",quote:"Rafaela is an excellent freelancer. She delivered ahead of schedule and was deeply committed, helpful, attentive and highly capable.",url:"https://www.workana.com/e/81d5c517a35449d394156e37c12e277f"},
 {name:"Leticia",project:"Canacaju",quote:"Highly competent, responsible and dedicated. Always available, kind and attentive. Perfect work. I strongly recommend her.",url:"https://www.workana.com/e/5d4732fff30f61ab914356a46500015a"},
 {name:"Marcelo Leite",quote:"A committed and patient professional. She met every requirement and delivered ahead of schedule. Fantastic work.",url:"https://www.workana.com/e/10c3c8fceaae5a52b951aeccc58a7143"},
 {name:"Larissa",quote:"An outstanding professional: punctual, communicative and open to improvements. Congratulations on the quality of the work.",url:"https://www.workana.com/e/d9163250b6f6d713f1acdac86b7f85df"},
 {name:"Fernand Stallone",project:"Visual identity",quote:"I highly recommend Rafaela. She was open to my changes, very agile and delivered before the deadline. I will certainly hire her again.",url:"https://www.workana.com/e/0e53e8c63c5673dd7ba3ec85b9cab5d3"},
 {name:"Camila Costa",project:"Ensinar Transforma",quote:"An excellent professional. She responded quickly, answered my questions and delivered the project exactly as I wanted."},
 {name:"Narayane",quote:"I highly recommend Rafaela. Very punctual. I loved the work she delivered.",url:"https://www.workana.com/e/7900df6cb4ab4f2047ab82144b4f5e7a"},
 {name:"Mauricio Schiaveto",quote:"Excellent professional. She delivered everything agreed upon. I recommend her work.",url:"https://www.workana.com/e/380c0670c723d1bdf6188834fd496fb2"},
 {name:"Elielton Fucks",quote:"Very attentive and committed to the work.",url:"https://www.workana.com/e/0ca6ede2fc9fb36fc30d29114f834eaf"},
 {name:"Pablo Penna",quote:"Very good work—the material was complete and detailed.",url:"https://www.workana.com/e/7d59681c1738f1d31b09fdccce5dfcb0"},
 {name:"Oriane Thaler",quote:"Very good work. She delivered the project progressively according to our needs until completion.",url:"https://www.workana.com/e/53530aef67a9f7d56c2534bce18e6619"},
 {name:"Kelly Aparecida de Andrade Silva",quote:"Rafaela’s work was very good.",url:"https://www.workana.com/e/c36f8a864c17ee4553aa6d45d558d3cb"},
 {name:"Nathan Eugenio",quote:"Good communication. I recommend her.",url:"https://www.workana.com/e/8a20138d16673d5495969bca3e9d4573"},
 {name:"Felipe Augusto",project:"Aiurotrek",quote:"The project came out just as I imagined. She translated my ideas exactly, organised the information clearly and achieved the aesthetic I wanted. It exceeded my expectations."}
];
export default function TestimonialsEn(){return <main><header className="siteHeader"><Link className="wordmark" href="/en">Rafaela Arantes</Link><nav><Link href="/en">Home</Link><Link href="/en/projects">Projects</Link><Link href="/en/education">Education</Link><Link href="/en/#about">About</Link><a href="mailto:rafaela.arantes.rj@gmail.com">Contact</a><Link className="languageSwitch" href="/depoimentos">PT</Link></nav></header><section className="pageHero"><p className="eyebrow">Client testimonials</p><h1>Real experiences, shared by those who trusted my work.</h1><p>Client feedback translated from Portuguese. When available, open the original Workana review.</p></section><section className="allTestimonials">{items.map((x,i)=><article key={x.name}><span className="testimonialNumber">{String(i+1).padStart(2,"0")}</span><blockquote>“{x.quote}”</blockquote><div className="testimonialPerson"><div><strong>{x.name}</strong>{x.project&&<span>{x.project}</span>}</div>{x.url?<a href={x.url} target="_blank" rel="noreferrer">View original review ↗</a>:<span className="direct">Testimonial received directly</span>}</div></article>)}</section><section className="contactClean compactContact"><p className="eyebrow">Your project could be next</p><h2>Shall we work together?</h2><a href="mailto:rafaela.arantes.rj@gmail.com">Get in touch ↗</a></section><footer className="siteFooter"><span>Rafaela Arantes © 2026</span><Link href="/en">Back to home ↑</Link></footer></main>}
