import type { Project } from "./projects";

export const projectsEn: Project[] = [
  {slug:"canacaju",title:"Canacaju",category:"Editorial design",year:"2024–2026",featured:true,summary:"Three seasons shaped into clear, desirable and consistent catalogues.",challenge:"Organise extensive swimwear collections into sales materials that are easy to navigate while preserving the brand’s personality and appeal.",role:"Visual direction, layout, information hierarchy and catalogue production.",deliverables:["Summer 2024 catalogue","Summer 2025 catalogue","Summer 2026 catalogue","Recurring editorial system"],cover:"/projects/canacaju.png",images:["/projects/canacaju.png"],documents:[{label:"View authorised catalogue sample",url:"/cases/canacaju/catalogo-2024.pdf"}],testimonial:{quote:"Highly competent, responsible and dedicated. Perfect work. I strongly recommend her.",name:"Leticia · Canacaju"}},
  {slug:"aiurotrek",title:"Aiurotrek",category:"Brand communication",year:"2026",featured:true,summary:"Complex expedition information transformed into a clear experience.",challenge:"Structure the itinerary, guidance and commercial information in a functional brochure that also conveyed the atmosphere of the experience.",role:"Brief interpretation, information architecture, visual direction and layout.",deliverables:["Institutional brochure","Content hierarchy","Visual direction"],cover:"/projects/aiurotrek.png",images:["/cases/aiuruotrek/brochure-front.png","/cases/aiuruotrek/brochure-open.png","/cases/aiuruotrek/folder.png"],testimonial:{quote:"She translated my ideas exactly. The information became clear, with the aesthetic I was looking for.",name:"Felipe Augusto · Aiurotrek"}},
  {slug:"pendulum-web",title:"Pendulum — Website banners",category:"Website campaign",year:"2025",featured:true,summary:"A campaign adapted for desktop and mobile with impact and clear reading.",challenge:"Maintain campaign impact and offer legibility across digital formats.",role:"Creative design and responsive campaign adaptations.",deliverables:["Website application","Desktop banner","Mobile banner"],cover:"/cases/pendulum/computer.png",images:["/cases/pendulum/computer.png","/cases/pendulum/desktop.png","/cases/pendulum/mobile.png"]},
  {slug:"pendulum-instagram",title:"Pendulum — Instagram",category:"Social media content",year:"2025",featured:true,summary:"Sophisticated visual direction for the brand’s Instagram presence.",challenge:"Translate the campaign into a clear, desirable social asset.",role:"Social asset design and campaign adaptation.",deliverables:["Instagram asset","Campaign adaptation"],cover:"/projects/pendulum-social.png",images:["/projects/pendulum-social.png","/cases/pendulum/instagram.png"]},
  {slug:"micaela-castaldi",title:"Micaela Castaldi",category:"Visual identity",year:"2026",featured:true,summary:"A sensitive, expressive personal brand for a psychology professional.",challenge:"Translate warmth and personality into a professional visual system without relying on the field’s most common clichés.",role:"Visual strategy, identity design, palette, typography and graphic elements.",deliverables:["Primary logo","Brand variations","Palette and typography","Graphic elements"],cover:"/projects/micaela.png",images:["/cases/micaela/identidade.png"]},
  {slug:"narayane-martins",title:"Narayane Martins",category:"Proposal design",year:"2025",summary:"A direct, organised commercial presentation aligned with her professional image.",challenge:"Turn a service proposal into material that was easy to understand and visually coherent.",role:"Visual direction and commercial presentation design.",deliverables:["Proposal cover","Editorial system","Presentation mock-up"],cover:"/projects/narayane.png",images:["/cases/narayane/mockup.png"],testimonial:{quote:"I highly recommend Rafaela. Very punctual. I loved the work she delivered.",name:"Narayane"}},
  {slug:"street-academia",title:"Street Academia",category:"Promotional design",year:"2025",summary:"A pricing table that organises plans, conditions and benefits for quick understanding.",challenge:"Present different plans, fees, opening hours and services in a single promotional asset without losing clarity or visual impact.",role:"Information organisation, visual hierarchy, composition and pricing-table design.",deliverables:["Pricing table","Plan hierarchy","Promotional asset"],cover:"/projects/street-academia.png",images:["/projects/street-academia.png"]},
  {slug:"doctomatic",title:"Doctomatic",category:"Social media",year:"2023",summary:"Spanish-language visual content introducing a remote patient-monitoring platform.",challenge:"Translate health-technology features into clear, approachable social assets aligned with the brand’s visual identity.",role:"Social asset design, visual composition and content organisation.",deliverables:["Institutional posts","Informational content","Seasonal asset","Feature presentation"],cover:"/projects/doctomatic.png",images:["/projects/doctomatic.png"]},
  {slug:"biodose-natural",title:"Biodose Natural",category:"Social media content",year:"2026",featured:true,summary:"A content system presenting natural products with clarity, consistency and visual appeal.",challenge:"Organise benefits, ingredients and contexts of use into an informative, light and recognisable social presence.",role:"Visual direction, composition, content hierarchy and Instagram asset design.",deliverables:["Visual direction","Instagram grid","Educational posts","Product presentation"],cover:"/projects/biodose-natural.png",images:["/projects/biodose-natural.png"]},
  {slug:"comunicacao-delivery",title:"Delivery Communication",category:"Social media content",year:"2026",featured:true,summary:"Direct, dynamic communication for an agile, safe and approachable delivery service.",challenge:"Turn the service differentiators into an easy-to-understand visual sequence suited to social media.",role:"Visual concept, message organisation, composition and social campaign design.",deliverables:["Instagram campaign","Post system","Informational content","Conversion calls"],cover:"/projects/comunicacao-delivery.png",images:["/projects/comunicacao-delivery.png"]},
  {slug:"ensinar-transforma",title:"Ensinar Transforma",category:"Visual identity",year:"2025",featured:false,summary:"An accessible, coherent identity for an education initiative.",challenge:"Create a welcoming, recognisable visual language that could be applied consistently across different touchpoints.",role:"Concept, visual identity, colour palette, typography and applications.",deliverables:["Logo and variations","Colour palette","Typography","Brand applications"],cover:"/cases/ensinar-transforma/identidade.pdf",coverKind:"pdf",documents:[{label:"View the identity presentation",url:"/cases/ensinar-transforma/identidade.pdf"}],testimonial:{quote:"An excellent professional. She responded quickly, answered my questions and delivered exactly what I wanted.",name:"Camila Costa"}}
];

export const getProjectEn = (slug: string) => projectsEn.find(project => project.slug === slug);
