import type { Project } from "./projects";

export const projectsEn: Project[] = [
  {slug:"canacaju",title:"Canacaju",category:"Editorial design",year:"2024–2026",featured:true,summary:"Three seasons shaped into clear, desirable and consistent catalogues.",challenge:"Organise extensive swimwear collections into sales materials that are easy to navigate while preserving the brand’s personality and appeal.",role:"Visual direction, layout, information hierarchy and catalogue production.",deliverables:["Summer 2024 catalogue","Summer 2025 catalogue","Summer 2026 catalogue","Recurring editorial system"],cover:"/projects/canacaju.png",images:["/projects/canacaju.png"],documents:[{label:"View authorised catalogue sample",url:"/cases/canacaju/catalogo-2024.pdf"}],testimonial:{quote:"Highly competent, responsible and dedicated. Perfect work. I strongly recommend her.",name:"Leticia · Canacaju"}},
  {slug:"aiurotrek",title:"Aiurotrek",category:"Brand communication",year:"2026",featured:true,summary:"Complex expedition information transformed into a clear experience.",challenge:"Structure the itinerary, guidance and commercial information in a functional brochure that also conveyed the atmosphere of the experience.",role:"Brief interpretation, information architecture, visual direction and layout.",deliverables:["Institutional brochure","Content hierarchy","Visual direction"],cover:"/projects/aiurotrek.png",images:["/projects/aiurotrek.png"],testimonial:{quote:"She translated my ideas exactly. The information became clear, with the aesthetic I was looking for.",name:"Felipe Augusto · Aiurotrek"}},
  {slug:"ensinar-transforma",title:"Ensinar Transforma",category:"Visual identity",year:"2025",featured:true,summary:"An accessible, coherent identity for an education initiative.",challenge:"Create a welcoming, recognisable visual language that could be applied consistently across different touchpoints.",role:"Concept, visual identity, colour palette, typography and applications.",deliverables:["Logo and variations","Colour palette","Typography","Brand applications"],cover:"/cases/ensinar-transforma/identidade.pdf",coverKind:"pdf",documents:[{label:"View the identity presentation",url:"/cases/ensinar-transforma/identidade.pdf"}],testimonial:{quote:"An excellent professional. She responded quickly, answered my questions and delivered exactly what I wanted.",name:"Camila Costa"}},
  {slug:"micaela-castaldi",title:"Micaela Castaldi",category:"Visual identity",year:"2026",featured:true,summary:"A sensitive, expressive personal brand for a psychology professional.",challenge:"Translate warmth and personality into a professional visual system without relying on the field’s most common clichés.",role:"Visual strategy, identity design, palette, typography and graphic elements.",deliverables:["Primary logo","Brand variations","Palette and typography","Graphic elements"],cover:"/projects/micaela.png",images:["/cases/micaela/identidade.png"]},
  {slug:"pendulum",title:"Pendulum",category:"Multi-format campaign",year:"2025",summary:"A banner system adapted for desktop, mobile and Instagram.",challenge:"Maintain the campaign’s impact and offer legibility across formats with different proportions and contexts.",role:"Creative design and responsive campaign adaptations. Website and brand identity were outside the scope.",deliverables:["Desktop banner","Mobile banner","Instagram asset"],cover:"/cases/pendulum/desktop.png",images:["/cases/pendulum/desktop.png","/cases/pendulum/mobile.png","/cases/pendulum/instagram.png"]},
  {slug:"narayane-martins",title:"Narayane Martins",category:"Proposal design",year:"2025",summary:"A direct, organised commercial presentation aligned with her professional image.",challenge:"Turn a service proposal into material that was easy to understand and visually coherent.",role:"Visual direction and commercial presentation design.",deliverables:["Proposal cover","Editorial system","Presentation mock-up"],cover:"/projects/narayane.png",images:["/cases/narayane/mockup.png"],testimonial:{quote:"I highly recommend Rafaela. Very punctual. I loved the work she delivered.",name:"Narayane"}},
  {slug:"street-academia",title:"Street Academia",category:"Promotional design",year:"2025",summary:"A pricing table that organises plans, conditions and benefits for quick understanding.",challenge:"Present different plans, fees, opening hours and services in a single promotional asset without losing clarity or visual impact.",role:"Information organisation, visual hierarchy, composition and pricing-table design.",deliverables:["Pricing table","Plan hierarchy","Promotional asset"],cover:"/projects/street-academia.png",images:["/projects/street-academia.png"]}
];

export const getProjectEn = (slug: string) => projectsEn.find(project => project.slug === slug);
