import Link from "next/link";
const education=[{title:"Bachelor’s degree in Psychology",institution:"Universidade Unigranrio",period:"2021 — 2025",logo:"/credentials/logos/unigranrio.jpg"},{title:"Digital Marketing",institution:"Universidade Veiga de Almeida",period:"2022 — 2025",logo:"/credentials/logos/uva.jpg"}];
const credentials=[
 {title:"B2B Marketing and Sales: Closing New Business",institution:"University of São Paulo",date:"March 2025",logo:"/credentials/logos/usp.jpg",url:"/credentials/docs/usp-b2b.jpg"},
 {title:"English Certificate — C2 Proficient",institution:"EF SET",date:"March 2025",logo:"/credentials/logos/efset.jpg",url:"https://cert.efset.org/en/zPUoB1"},
 {title:"Foundations of Digital Marketing and E-commerce",institution:"Google",date:"March 2023",logo:"/credentials/logos/google.jpg",url:"/credentials/docs/google-marketing.jpg"},
 {title:"Advanced Branding: Analysing Brand Effectiveness",institution:"Conquer",date:"August 2023",logo:"/credentials/logos/conquer.jpg",url:"/credentials/docs/conquer-branding.jpg"},
 {title:"Customer Experience (CX)",institution:"Conquer",date:"August 2023",logo:"/credentials/logos/conquer.jpg",url:"/credentials/docs/conquer-cx.jpg"},
 {title:"Digital Marketing",institution:"University of São Paulo",date:"April 2022",logo:"/credentials/logos/usp.jpg",url:"/credentials/docs/usp-marketing-digital.jpeg"},
 {title:"Product and Brand",institution:"FGV Online",date:"Further education",logo:"/credentials/logos/fgv.jpg",url:"/credentials/docs/fgv-produto-marca.pdf"},
 {title:"Global Marketing: Building Iconic Brands",institution:"University of Illinois · Coursera",date:"Further education",logo:"/credentials/logos/illinois.jpg",url:"/credentials/docs/illinois-global-marketing.pdf"}
];
export default function EducationEn(){return <main><header className="siteHeader"><Link className="wordmark" href="/en">Rafaela Arantes</Link><nav><Link href="/en">Home</Link><Link href="/en/projects">Projects</Link><Link href="/en/testimonials">Testimonials</Link><a href="mailto:rafaela.arantes.rj@gmail.com">Contact</a><Link className="languageSwitch" href="/formacao">PT</Link></nav></header><section className="pageHero educationHero"><p className="eyebrow">Education & credentials</p><h1>A background connecting behaviour, strategy and creativity.</h1><p>My education combines Psychology and Digital Marketing, complemented by studies in branding, business, customer experience and communication.</p></section><section className="educationSection"><header><p className="eyebrow">Academic education</p><span>Degrees</span></header><div className="educationGrid">{education.map(x=><article key={x.title}><img src={x.logo} alt={`${x.institution} logo`}/><div><h2>{x.title}</h2><p>{x.institution}</p><span>{x.period}</span></div></article>)}</div></section><section className="credentialsSection"><header><p className="eyebrow">Courses & certifications</p><span>{credentials.length} selected credentials</span></header><div className="credentialRows">{credentials.map(x=><article key={x.title}><img src={x.logo} alt={`${x.institution} logo`}/><div className="credentialCopy"><h2>{x.title}</h2><p>{x.institution}</p><span>{x.date}</span></div><a href={x.url} target="_blank" rel="noreferrer">View credential ↗</a></article>)}</div></section><section className="contactClean compactContact"><p className="eyebrow">Beyond certificates</p><h2>See how this knowledge shapes my work.</h2><Link href="/en/projects">Explore projects ↗</Link></section><footer className="siteFooter"><span>Rafaela Arantes © 2026</span><Link href="/en">Back to home ↑</Link></footer></main>}
