import Link from "next/link";
import { projectsEn } from "../projects-en";

const testimonials=[
  {quote:"Highly competent, responsible and dedicated. Perfect work. I strongly recommend her.",name:"Leticia",project:"Canacaju"},
  {quote:"An outstanding professional: punctual, open to improvements and communicative.",name:"Larissa",project:"Workana client"},
  {quote:"She met every requirement and delivered ahead of schedule.",name:"Marcelo Leite",project:"Workana client"}
];

export default function HomeEn(){return <main>
  <header className="siteHeader"><Link className="wordmark" href="/en">Rafaela Arantes</Link><nav aria-label="Main navigation"><Link href="/en/projects">Projects</Link><a href="#about">About</a><Link href="/en/education">Education</Link><Link href="/en/testimonials">Testimonials</Link><a href="mailto:rafaela.arantes.rj@gmail.com">Contact</a><Link className="languageSwitch" href="/" aria-label="Ver site em português">PT</Link></nav></header>
  <section className="heroClean"><p className="eyebrow">Brand strategy · design · content</p><h1>I turn ideas into clear, relevant and memorable brands.</h1><div className="heroIntro"><p>Strategy, design and content for brands that want to communicate with clarity and personality.</p><a className="button" href="#projects">Explore my work</a></div></section>
  <section className="section" id="projects"><div className="sectionHeading"><p className="eyebrow">Selected projects</p><h2>Purposeful work, from strategy to delivery.</h2></div><div className="projectGrid">{projectsEn.filter(p=>p.featured).map((p,i)=><Link className="projectCard" href={`/en/projects/${p.slug}`} key={p.slug}><div className="projectVisual">{p.coverKind==="pdf"?<iframe src={`${p.cover}#page=1&view=Fit&zoom=page-fit&toolbar=0`} title={`${p.title} project preview`} tabIndex={-1}/>:<img src={p.cover} alt={`${p.title} project`}/>}<span className="viewProject">View case ↗</span></div><div className="projectInfo"><span>{String(i+1).padStart(2,"0")} · {p.category}</span><h3>{p.title}</h3><p>{p.summary}</p></div></Link>)}</div><div className="sectionAction"><Link className="button" href="/en/projects">View all 7 projects</Link></div></section>
  <section className="section servicesClean"><div className="sectionHeading"><p className="eyebrow">How I can help</p><h2>An integrated perspective for building presence.</h2></div><div className="simpleRows"><article><span>01</span><h3>Brand & identity</h3><p>Visual positioning, identity systems and creative direction.</p></article><article><span>02</span><h3>Content & social</h3><p>Strategy, campaigns and content that express the brand’s voice.</p></article><article><span>03</span><h3>Digital experiences</h3><p>Editorial materials, landing pages and digital communication.</p></article></div></section>
  <section className="section aboutClean" id="about"><div><p className="eyebrow">About me</p><h2>Strategy with sensitivity. Creativity with method.</h2></div><div className="bodyCopy"><p>I’m Rafaela Arantes, a brand and digital presence professional. My background in Digital Marketing and Psychology helps me see brands as systems of perception, communication and experience—not merely aesthetics.</p><p>Since 2022, I have worked across independent projects and institutional environments, connecting design, content and strategy in Portuguese and English.</p><p>I also work as a clinical psychologist, registered under CRP 05/85694, with a professional presence on Doctoralia.</p><div className="aboutLinks"><Link className="textLink" href="/en/education">Education & credentials ↗</Link><a className="textLink" href="https://linkedin.com/in/rafaelaamelo">Career on LinkedIn ↗</a></div></div></section>
  <section className="section testimonialPreview"><div className="sectionHeading testimonialHeading"><p className="eyebrow">Testimonials</p><h2>Trust built through every project.</h2><p>Real client feedback, with links to the original reviews.</p></div><div className="previewGrid">{testimonials.map(x=><article key={x.name}><blockquote>“{x.quote}”</blockquote><footer><strong>{x.name}</strong><span>{x.project}</span></footer></article>)}</div><Link className="button buttonLight" href="/en/testimonials">View all 14 testimonials</Link></section>
  <section className="contactClean"><p className="eyebrow">Let’s talk</p><h2>Have an idea or opportunity in mind?</h2><a href="mailto:rafaela.arantes.rj@gmail.com">rafaela.arantes.rj@gmail.com ↗</a></section><footer className="siteFooter"><span>Rafaela Arantes © 2026</span><span>Brand · Design · Content</span></footer>
</main>}
